#!/usr/bin/env python

import argparse

import sys
import os

sys.path.append("../")
os.environ['NOSE_REDNOSE'] = '1'


if __name__ == '__main__':

    default_parser = argparse.ArgumentParser(description="CLI for VSD Software Development Kit", add_help=False)
    default_parser.add_argument('-v', '--verbose', help='Activate verbose mode', action='store_true')
    default_parser.add_argument('-u', '--username', help='username to get an api key or set `VSDK_USERNAME` in your variable environment')
    default_parser.add_argument('-p', '--password', help='password to get an api key or set `VSDK_PASSWORD` in your variable environment')
    default_parser.add_argument('--api', help='URL of the API endpoint or set `VSDK_API_URL` in your variable environment')
    default_parser.add_argument('-e', '--enterprise', help='Name of the enterprise to connect or set `VSDK_ENTERPRISE` in your variable environment')


    parser = argparse.ArgumentParser(description="Usage: vsdk-cli {command} {arguments} ")
    subparsers = parser.add_subparsers(dest="command",
                                       title='Command',
                                       description='See commands description below',
                                       help='list of available commands')

    # List all enterprises command
    subparser = subparsers.add_parser('list_enterprises', parents=[default_parser], help="List all enterprises for the current user")

    # Show enterprise
    subparser = subparsers.add_parser('show_enterprise', parents=[default_parser], help="Another command")
    subparser.add_argument('-i', '--id', help='Identifier of the enterprise to show', required=True)

    args = parser.parse_args()

    from commands import VSDKCommands
    VSDKCommands.execute(args)
